### ISSUE TITLE
Build iris on OS X

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/iris-feedstock#1]
Right now we had to skip due to https://github.com/conda-forge/staged-recipes/pull/280#issuecomment-206377121

**Comment by ocefpaf** [comment]
More on this: https://github.com/SciTools/conda-recipes-scitools/pull/140

**Comment by jakirkham** [comment]
Could you please give me the cliff notes version of what is going on here, @ocefpaf? I can't promise I'll look at today, but I will try to look at it soon.

**Comment by ocefpaf** [comment]
See #2
