### ISSUE TITLE
Depend on mo-pack, and remove the unpacking C library

### ISSUE THREAD

**Issue by pelson** [conda-forge/iris-feedstock#3]
It will reduce the build matrix, and offers performance as well. https://github.com/SciTools/conda-recipes-scitools/tree/master/mo_pack

**Comment by ocefpaf** [comment]
We already have a [feedstock](https://github.com/conda-forge/mo_pack-feedstock) for `mo_pack` BTW.

**Comment by pelson** [comment]
Done.
