### ISSUE TITLE
error- 'iris' is not a package

### ISSUE THREAD

**Issue by LewisB7** [conda-forge/iris-feedstock#9]
Hi,

I have installed iris using: conda install -c conda-forge iris

When I run a script in Spyder (Python 3.5) with import iris.plot I get the error message:
ImportError: No module named 'iris.plot'; 'iris' is not a package

I am not sure why this is. Assistance would be much appreciated.

**Comment by ocefpaf** [comment]
Can you import `iris.plot` outside `spyder`? Did you install both `iris` and `spyder` with conda? in the root or in a separate env?

I am not a `spyder` user to help you much there... Sorry. But if you can import `iris.plot` outside `spyder` I believe that the package here is not at fault.

**Comment by LewisB7** [comment]
I could not import iris.plot inside or outside of spyder.
spyder comes with the installation of anaconda.
I am installing iris to my root environment.

I am now able to use iris both inside and outside spyder after doing: conda install -c conda-forge iris

I have now added conda-forge to my .condarc file. I believe that may have been the problem.

**Comment by ocefpaf** [comment]
> I am now able to use iris both inside and outside spyder after doing: conda install -c conda-forge iris

Nice!

> I have now added conda-forge to my .condarc file. I believe that may have been the problem.

If you want a one time install the `-c conda-forge` should be OK. But adding it to your `.condarc` is probably better so you can update and always get the latest version. Closing this. Please re-open if you need help.
